export type RealmKind = 'roots' | 'winter' | 'garden' | 'workshop' | 'academy' | 'harbor' | 'bridges' | 'theater' | 'lanterns' | 'sun';

// Lore informs architecture, colors, and activity; it is not shown as page copy.
export const TREE_REALMS: { progress: number; name: string; kind: RealmKind; angle: number; y: number; radius: number; lore: string; ground: string; walls: string; roof: string; accent: string; horizon: string; zenith: string }[] = [
  { progress: 1, name: 'Rootbound Underworld', kind: 'roots', angle: 0.38, y: -35, radius: 36, lore: 'Root keepers shelter beneath the island among ancient exposed roots and falling snow.', ground: '#aabdc4', walls: '#617783', roof: '#315b63', accent: '#a9e7d4', horizon: '#344b5c', zenith: '#162a38' },
  { progress: 2, name: 'Frosthaven', kind: 'winter', angle: 0.95, y: 18, radius: 48, lore: 'A sheltered winter settlement of timber lodges, snowfall, and warm hearths.', ground: '#dbeaf6', walls: '#789aaf', roof: '#e8f4ff', accent: '#ffbc67', horizon: '#abcfe8', zenith: '#416b9d' },
  { progress: 3, name: 'Bloomgrove', kind: 'garden', angle: 1.7, y: 29, radius: 54, lore: 'Orchard tenders grow blossoms and medicinal plants on hanging terraces.', ground: '#438451', walls: '#d7c597', roof: '#427758', accent: '#ff91b8', horizon: '#9bd9c6', zenith: '#32849c' },
  { progress: 4, name: 'Copperleaf', kind: 'workshop', angle: 2.45, y: 39, radius: 60, lore: 'Makers power their workshops with wind and share tools around a brass mill.', ground: '#50714a', walls: '#c39761', roof: '#9a5438', accent: '#ffce75', horizon: '#acd2bd', zenith: '#407c94' },
  { progress: 5, name: 'Skyward Academy', kind: 'academy', angle: 3.1, y: 49, radius: 63, lore: 'Cloud scholars gather beneath teal spires and chart the sky with an orrery.', ground: '#7da5a0', walls: '#e3dfc7', roof: '#168e99', accent: '#b6fcff', horizon: '#b4e2e6', zenith: '#337cae' },
  { progress: 7, name: 'Tideglass', kind: 'harbor', angle: 4.1, y: 61, radius: 65, lore: 'Water archivists carry messages through a canal harbor fed by a branch spring.', ground: '#447d8e', walls: '#d4dec4', roof: '#197eaf', accent: '#6beddc', horizon: '#8fd2df', zenith: '#25689d' },
  { progress: 8, name: 'Bridgeward', kind: 'bridges', angle: 4.8, y: 71, radius: 65, lore: 'Couriers connect twin neighborhoods across a suspended timber bridge.', ground: '#41865d', walls: '#d7b47e', roof: '#227955', accent: '#d9ea8e', horizon: '#99d2b9', zenith: '#347d91' },
  { progress: 9, name: 'Starfall', kind: 'theater', angle: 5.5, y: 81, radius: 60, lore: 'Performers and stargazers share an open theater beneath violet observatory domes.', ground: '#5a577e', walls: '#a8a4cf', roof: '#674697', accent: '#d9b5ff', horizon: '#888cae', zenith: '#343f71' },
  { progress: 10, name: 'Emberlight', kind: 'lanterns', angle: 6.1, y: 89, radius: 51, lore: 'Neighbors meet in lantern streets and carry warm lights through the evening market.', ground: '#766141', walls: '#b87851', roof: '#a84439', accent: '#ffc76e', horizon: '#d3ac91', zenith: '#6c6797' },
  { progress: 11, name: 'Solarium', kind: 'sun', angle: 6.8, y: 101, radius: 32, lore: 'Crown stewards welcome travelers into a golden sanctuary above the clouds.', ground: '#ccbb7d', walls: '#f1e6c9', roof: '#d1a646', accent: '#ffe8a3', horizon: '#ecd4a2', zenith: '#6faac1' },
];
